name: Mirroring

on: [push, delete]

jobs:
  to_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{vars.REMOTE_URL}}
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Check the repository's name
        run: |
          if [ "${{ github.ref_name }}" = "no-ga" ]; then
            exit 1
          fi
          if [ "${{ github.event.repository.ssh_url }} = ${{vars.REMOTE_URL}}"]; then
            exit 1
          fi
      - name: Get ssh url
        run: echo 