name: Chocolatine project
on: [push, delete]

jobs:
  check_remote_is_valid:
    runs-on: ubuntu-latest
    steps:
      - name: Check the repository's name
        run: |
          if [ "${{ github.ref_name }}" = "no-ga" ]; then
            exit 1
          fi
      - name : Check if it's the same repository
        run: |
          if [ "${{ github.event.repository.ssh_url }}" = "${{vars.MIRROR_SSH_URL}}" ]; then
            exit 1
          fi
  check_compilation_and_coding_style:
    runs-on: ubuntu-latest
    needs: check_remote_is_valid
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: copy_repository_in_dir
        run: |
          mkdir -p /app
          cp -r $GITHUB_WORKSPACE/* /app/
      - name: check_infractions
        run: banana-check-repo
      - name: compilation
        run: make
        working-directory: ${{ github.workspace }}
        timeout-minutes: 2
  clone_to_branch:
    runs-on: ubuntu-latest
    needs: [check_remote_is_valid, check_compilation_and_coding_style]
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{vars.MIRROR_SSH_URL}}
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}