name: Get repository size

on:
  push:
    branches:
      - main
jobs:
    get_size:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v6.0.2
            with:
                -sparse-checkout: .
          - name: Get size
            run: echo ${{ github.workspace }}